---
name: Themes

on:
  push:
    branches:
      - master
    paths:
      - 'CTFd/themes/**'
  pull_request:
    branches:
      - master
    paths:
      - 'CTFd/themes/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build themes

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: yarn
          cache-dependency-path: |
            CTFd/themes/admin/yarn.lock
            CTFd/themes/core/yarn.lock

      - name: Core theme
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
          yarn build
          yarn build:lib
        working-directory: ./CTFd/themes/core

      - name: Admin theme
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
        working-directory: ./CTFd/themes/admin
